import {demoVendors,categories,demoServices} from './demo-data.js';

// Internal-only data mode: every action is saved in this browser's localStorage.
// It intentionally avoids Firebase/Firestore, so there are no remote permissions
// or rules to configure. Data is private to this browser and is not shared online.
const STORE_KEY='shirwal-circle-internal-v1';
const SESSION_KEY='shirwal-circle-session';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const id=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const now=()=>Date.now();
const status=text=>{const element=$('#status');if(element){element.textContent=text;element.classList.remove('hidden')}};

function seed(){
  const vendorUser={id:'local-vendor-user',name:'Shirwal Demo Vendor',email:'vendor@shirwal.local',password:'vendor123',role:'vendor',status:'active'};
  const admin={id:'local-admin',name:'Shirwal Admin',email:'admin@shirwal.local',password:'admin123',role:'admin',status:'active'};
  const vendor={id:'local-vendor',ownerId:vendorUser.id,ownerName:vendorUser.name,name:'Local Service Demo',category:'Home Services',description:'An internal demo business for testing the vendor booking workspace.',location:'Shirwal',hours:'Mon–Sat · 9 AM–6 PM',phone:'919000000000',bookingEnabled:true,status:'approved',verified:true,rating:5,icon:'🏪'};
  return {users:[admin,vendorUser],vendors:[vendor],bookings:[],conversations:[],messages:[]};
}
// Removes the unwanted legacy listing requested for this internal workspace once.
function migrate(store){
  let changed=false;
  if(!store.migrations?.removeKartikListing){
    store.vendors=store.vendors.filter(vendor=>String(vendor.name||'').trim().toLowerCase()!=='kartik');
    store.migrations={...(store.migrations||{}),removeKartikListing:true};
    changed=true;
  }
  // Existing internal listings created before immediate vendor access are promoted
  // so their owners can see their vendor workspace without recreating the listing.
  if(!store.migrations?.promoteExistingVendors){
    store.vendors.forEach(vendor=>{
      if(vendor.status==='pending') vendor.status='approved';
      const owner=store.users.find(user=>user.id===vendor.ownerId);
      if(owner) owner.role='vendor';
    });
    store.migrations={...(store.migrations||{}),promoteExistingVendors:true};
    changed=true;
  }
  if(changed) localStorage.setItem(STORE_KEY,JSON.stringify(store));
  return store;
}
function data(){try{return migrate(JSON.parse(localStorage.getItem(STORE_KEY))||seed())}catch{return seed()}}
function save(next){localStorage.setItem(STORE_KEY,JSON.stringify(next))}
function session(){const userId=localStorage.getItem(SESSION_KEY);return data().users.find(user=>user.id===userId)||null}
let currentUser=session();
function updateUser(user){const store=data();const index=store.users.findIndex(item=>item.id===user.id);if(index>-1){store.users[index]=user;save(store)}currentUser=user}
// The internal vendor owns the seeded demo services, so vendor booking testing works.
function allVendors(){return [...demoVendors.map(vendor=>({...vendor,ownerId:'local-vendor-user',status:'approved'})),...data().vendors.filter(vendor=>vendor.status==='approved')]}
function ownedVendorIds(userId){return new Set(allVendors().filter(vendor=>vendor.ownerId===userId).map(vendor=>vendor.id))}
function roleDestination(user){return user?.role==='admin'?'admin-dashboard.html':user?.role==='vendor'?'vendor-dashboard.html':'account.html'}

function nav(){const page=location.pathname.split('/').pop()||'index.html';const role=currentUser?.role;const action=role==='vendor'?'vendor-dashboard.html':role==='admin'?'admin-dashboard.html':'submit-business.html';const active=target=>page===target?'active':'';const mobile=role==='vendor'?[['vendor-dashboard.html','▦','Home'],['vendor-bookings.html','◷','Bookings'],[action,'+',''],['vendor-chat.html','◌','Chat'],['account.html','♙','Account']]:role==='admin'?[['admin-dashboard.html','▦','Home'],['vendors.html','⌕','Vendors'],[action,'+',''],['bookings.html','◷','Bookings'],['account.html','♙','Account']]:[['index.html','⌂','Home'],['vendors.html','⌕','Search'],[action,'+',''],['chat.html','◌','Chat'],['account.html','♙','Account']];return `<header class="topbar"><div class="shell"><a class="brand" href="index.html">🧿 Shirwal <span>Circle</span></a><nav class="desktop-nav"><a class="${active('index.html')}" href="index.html">Home</a><a class="${active('vendors.html')}" href="vendors.html">Services</a><a href="submit-business.html">For vendors</a><a class="${active('chat.html')}" href="chat.html">Chat</a></nav><a class="btn secondary" href="${currentUser?'account.html':'login.html'}">${currentUser?'My account':'Sign in'}</a></div></header><nav class="mobile-island" aria-label="Mobile navigation">${mobile.map(([href,icon,label],index)=>`<a class="${index===2?'plus':active(href)}" href="${href}" aria-label="${label||'Action'}"><span class="icon">${icon}</span>${label}</a>`).join('')}</nav>`}
function footer(){return `<footer class="footer"><div class="shell"><div class="brand">🧿 Shirwal Circle</div><p>Everything Shirwal needs. Right around the Circle.</p><small>Internal browser demo · No online payments.</small></div></footer>`}
function render(content){$('#app').innerHTML=nav()+`<main>${content}</main>`+footer()}
function requireUser(next){if(!currentUser){location.href=`login.html?next=${encodeURIComponent(next||location.pathname.split('/').pop())}`;return false}return true}

function vendorCard(vendor){const avatar=vendor.logo?`<img src="${esc(vendor.logo)}" alt="" loading="lazy">`:vendor.icon||'🏪';return `<article class="card vendor-card"><div class="vendor-top"><div class="avatar">${avatar}</div><div><span class="badge">✓ VERIFIED</span><br><b>${esc(vendor.name)}</b><div class="meta">★ ${vendor.rating||'New'} · 📍 ${esc(vendor.location||'Shirwal')}</div></div></div><div class="info"><p class="muted">${esc(vendor.description||'Trusted local service.')}</p><div class="meta"><span class="badge">● Available today</span></div><div class="card-actions"><a class="btn secondary" href="vendor.html?id=${vendor.id}">View details</a><a class="btn" href="request.html?vendor=${vendor.id}">${vendor.bookingEnabled?'Book':'Request'}</a></div></div></article>`}
function home(){render(`<section class="hero"><div class="shell hero-grid"><div><div class="eyebrow">Shirwal’s local marketplace</div><h1>Everything Shirwal needs.<br><em>Right around the Circle.</em></h1><p class="lead">Discover trusted local businesses, book services, and connect directly with providers in Shirwal.</p><form class="searchbar" id="heroSearch"><input aria-label="Search services" placeholder="What are you looking for? Doctor, Tiffin, Electrician…"><button class="btn">Explore</button></form><div class="actions" style="margin-top:22px"><a class="btn" href="vendors.html">Explore Services</a><a class="btn secondary" href="submit-business.html">Become a Vendor</a></div></div><aside class="hero-card"><div class="float-card">🍱 <span>Tiffin<small>Daily meals</small></span></div><div class="float-card">🔧 <span>Electrical<small>Home repairs</small></span></div><div class="float-card">🛺 <span>Rickshaw<small>Local rides</small></span></div><div class="float-card">🏥 <span>Health<small>Care nearby</small></span></div></aside></div></section><section class="section shell"><div class="section-head"><h2>Browse categories</h2><a href="vendors.html" class="muted">See all →</a></div><div class="grid">${categories.slice(0,9).map((category,index)=>`<a class="category" href="vendors.html?category=${encodeURIComponent(category)}"><span>${['🍱','🧺','🛺','🩺','✂️','💡','🔧','🚐','🏠'][index]}</span><b>${category}</b><small class="muted">Local providers</small></a>`).join('')}</div></section><section class="section shell"><div class="section-head"><h2>Popular near you</h2><a href="vendors.html" class="btn secondary">Explore all</a></div><div class="grid">${allVendors().slice(0,3).map(vendorCard).join('')}</div></section>`);$('#heroSearch').onsubmit=event=>{event.preventDefault();location.href=`vendors.html?q=${encodeURIComponent(event.target.querySelector('input').value)}`}}
function directory(){render(`<div class="shell directory"><div class="page-title"><div class="eyebrow">Shirwal service directory</div><h1>All services in Shirwal</h1><p class="muted">Browse local services and send a request without any online payment.</p></div><div class="filters"><input id="search" class="input" placeholder="Search business, service or category"><select id="category" class="input"><option value="">All categories</option>${categories.map(category=>`<option>${category}</option>`).join('')}</select><select id="sort" class="input"><option value="rating">Top rated</option><option value="name">Name A–Z</option></select></div><div id="vendorGrid" class="grid"></div></div>`);const draw=()=>{const queryText=$('#search').value.toLowerCase();const category=$('#category').value;const vendors=allVendors().filter(vendor=>(!category||vendor.category===category)&&`${vendor.name} ${vendor.category} ${vendor.description}`.toLowerCase().includes(queryText)).sort((a,b)=>$('#sort').value==='name'?a.name.localeCompare(b.name):(b.rating||0)-(a.rating||0));$('#vendorGrid').innerHTML=vendors.length?vendors.map(vendorCard).join(''):'<div class="empty">No vendors found. Try another search or category.</div>'};['search','category','sort'].forEach(name=>$('#'+name).addEventListener('input',draw));const params=new URLSearchParams(location.search);$('#search').value=params.get('q')||'';$('#category').value=params.get('category')||'';draw()}
function profile(){const vendor=allVendors().find(item=>item.id===new URLSearchParams(location.search).get('id'))||allVendors()[0];const services=demoServices.filter(service=>service.vendorId===vendor.id);render(`<div class="shell detail"><section><a class="muted" href="vendors.html">← All businesses</a><div class="card panel" style="margin-top:15px"><div class="vendor-top"><div class="avatar">${vendor.icon||'🏪'}</div><div><h1 style="margin:0">${esc(vendor.name)}</h1><div class="meta"><span class="badge">✓ Verified</span> ★ ${vendor.rating||'New'} · ${esc(vendor.category)}</div></div></div><p>${esc(vendor.description)}</p><p class="muted">📍 ${esc(vendor.location)}<br>🕒 ${esc(vendor.hours||'Hours shared on request')}</p><div class="actions"><a class="btn" href="request.html?vendor=${vendor.id}">${vendor.bookingEnabled?'Book appointment':'Request service'}</a><button class="btn secondary" id="chatButton">Chat</button><a class="btn secondary" href="tel:${vendor.phone||''}">Call</a></div></div><div class="card panel" style="margin-top:20px"><h2>Services</h2>${services.length?services.map(service=>`<div class="service-row"><span><b>${service.name}</b><br><small class="muted">${service.duration}</small></span><span><b>${service.price}</b><br><a class="muted" href="request.html?vendor=${vendor.id}&service=${service.id}">Select →</a></span></div>`).join(''):'<div class="empty">This business takes service requests directly.</div>'}</div></section></div>`);$('#chatButton').onclick=()=>startChat(vendor)}
function request(){const vendor=allVendors().find(item=>item.id===new URLSearchParams(location.search).get('vendor'))||allVendors()[0];const vendorServices=demoServices.filter(service=>service.vendorId===vendor.id);render(`<div class="shell"><div class="auth card"><div class="eyebrow">No payment required</div><h1>${vendor.bookingEnabled?'Book an appointment':'Request a service'}</h1><p class="muted">Send a request to <b>${esc(vendor.name)}</b>. The provider confirms it directly.</p><form id="bookingForm" class="stack"><label>Service<select class="input" name="service">${(vendorServices.length?vendorServices:[{id:'request',name:'General service request'}]).map(service=>`<option value="${service.id}">${service.name}</option>`).join('')}</select></label><label>Preferred date<input required type="date" min="${new Date().toISOString().slice(0,10)}" name="date" class="input"></label><label>Preferred time<select name="time" class="input"><option>09:00 AM</option><option>10:30 AM</option><option>01:00 PM</option><option>04:00 PM</option><option>06:00 PM</option></select></label><label>Tell the provider what you need<textarea class="input" name="note" rows="3"></textarea></label><div id="status" class="notice hidden"></div><button class="btn">Submit request</button></form></div></div>`);$('#bookingForm').onsubmit=event=>createBooking(event,vendor)}
function createBooking(event,vendor){event.preventDefault();if(!requireUser('request.html'+location.search))return;const form=new FormData(event.target);const service=demoServices.find(item=>item.id===form.get('service'))||{id:form.get('service'),name:'General service request'};const store=data();store.bookings.unshift({id:id('booking'),userId:currentUser.id,vendorId:vendor.id,serviceId:service.id,vendorName:vendor.name,serviceName:service.name,customerName:currentUser.name,customerContact:currentUser.phone||'',date:form.get('date'),time:form.get('time'),note:form.get('note')||'',status:'pending',createdAt:now()});save(store);location.href='bookings.html'}
function authPage(kind){const login=kind==='login';render(`<div class="auth card"><div class="eyebrow">Internal browser workspace</div><h1>${login?'Sign in':'Create your account'}</h1><form class="stack" id="authForm">${login?'':'<label>Your name<input class="input" required name="name" placeholder="Your full name"></label>'}<label>Email<input class="input" required name="email" type="email" placeholder="you@example.com"></label><label>Password<input class="input" required name="password" type="password" minlength="6" placeholder="At least 6 characters"></label><div id="status" class="notice hidden"></div><button class="btn">${login?'Sign in':'Create account'}</button></form><p class="muted">${login?'New here? <a href="register.html">Create an account</a>':'Already registered? <a href="login.html">Sign in</a>'}</p><p class="muted"><small>Internal demo accounts: admin@shirwal.local / admin123 and vendor@shirwal.local / vendor123.</small></p></div>`);$('#authForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target);const email=String(form.get('email')).trim().toLowerCase();const password=String(form.get('password'));const store=data();let user=store.users.find(item=>item.email===email);if(login){if(!user||user.password!==password)return status('Email or password is incorrect.');}else{if(user)return status('An account with this email already exists.');user={id:id('user'),name:String(form.get('name')).trim(),email,password,role:'user',status:'active',createdAt:now()};store.users.push(user);save(store)}localStorage.setItem(SESSION_KEY,user.id);currentUser=user;location.href=new URLSearchParams(location.search).get('next')||roleDestination(user)}}
function logout(){localStorage.removeItem(SESSION_KEY);currentUser=null;location.href='index.html'}
function account(){if(!requireUser('account.html'))return;render(`<div class="shell"><div class="page-title"><div class="eyebrow">Your circle</div><h1>Hello, ${esc(currentUser.name)}.</h1><p class="muted">This browser keeps your internal Shirwal Circle workspace.</p></div><div class="grid"><a class="category" href="bookings.html">📅<b>My bookings</b><small class="muted">Appointments and requests</small></a><a class="category" href="chat.html">💬<b>My chats</b><small class="muted">Talk to providers</small></a><a class="category" href="submit-business.html">🏪<b>List a business</b><small class="muted">Apply as a vendor</small></a></div><div class="card panel" style="margin-top:20px"><b>Account settings</b><p class="muted">Role: ${currentUser.role}</p><button class="btn secondary" id="logout">Log out</button></div></div>`);$('#logout').onclick=logout}
function bookingRows(bookings,actions=false){return bookings.length?bookings.map(booking=>`<div class="booking-row"><span><b>${esc(booking.serviceName)}</b><br><small class="muted">${esc(booking.vendorName)} · ${esc(booking.date)} · ${esc(booking.time)}<br>${esc(booking.note||'No note')}</small></span><span class="admin-actions"><span class="tag">${esc(booking.status)}</span>${actions&&booking.status==='pending'?`<button class="btn booking-status" data-id="${booking.id}" data-status="confirmed">Accept</button><button class="btn secondary booking-status" data-id="${booking.id}" data-status="rejected">Reject</button>`:''}${actions&&booking.status==='confirmed'?`<button class="btn secondary booking-status" data-id="${booking.id}" data-status="completed">Complete</button>`:''}${!actions&&booking.status==='pending'?`<button class="btn secondary cancel" data-id="${booking.id}">Cancel</button>`:''}</span></div>`).join(''):'<div class="empty">No bookings yet. Find a local business to get started.</div>'}
function changeBooking(idValue,statusValue){const store=data();const booking=store.bookings.find(item=>item.id===idValue);if(booking){booking.status=statusValue;save(store)}}
function bookings(){
  if(!requireUser('bookings.html'))return;
  const store=data();
  const isAdmin=currentUser.role==='admin';
  const isVendor=currentUser.role==='vendor';
  const visible=isAdmin?store.bookings:isVendor?store.bookings.filter(booking=>ownedVendorIds(currentUser.id).has(booking.vendorId)):store.bookings.filter(booking=>booking.userId===currentUser.id);
  const heading=isAdmin?'All bookings':isVendor?'Business bookings':'My bookings';
  render(`<div class="shell"><div class="page-title"><div class="eyebrow">${isAdmin?'Admin inbox':isVendor?'Vendor workspace':'Your reservations'}</div><h1>${heading}</h1><p class="muted">${isAdmin?'Every internal booking request is visible here.':isVendor?'Requests for your businesses are visible here.':'No payments are collected on Shirwal Circle.'}</p></div><div id="bookingList" class="card panel">${bookingRows(visible,isVendor)}</div></div>`);
  document.querySelectorAll('.cancel').forEach(button=>button.onclick=()=>{changeBooking(button.dataset.id,'cancelled');bookings()});
  document.querySelectorAll('.booking-status').forEach(button=>button.onclick=()=>{changeBooking(button.dataset.id,button.dataset.status);bookings()});
}
function submitBusiness(){if(!requireUser('submit-business.html'))return;render(`<div class="shell"><div class="auth card" style="max-width:700px"><div class="eyebrow">Join local businesses</div><h1>List your business</h1><p class="muted">In internal mode, your listing is available immediately and your account becomes a vendor account.</p><form id="businessForm" class="stack"><div class="grid"><label>Owner name<input required name="ownerName" class="input" value="${esc(currentUser.name)}"></label><label>Phone / WhatsApp<input required name="phone" class="input"></label></div><label>Business name<input required name="name" class="input"></label><label>Category<select required name="category" class="input">${categories.map(category=>`<option>${category}</option>`).join('')}</select></label><label>Description<textarea required name="description" class="input" rows="3"></textarea></label><div class="grid"><label>Address<input required name="location" class="input"></label><label>Opening hours<input required name="hours" class="input"></label></div><label><input type="checkbox" name="bookingEnabled"> I accept appointment booking requests</label><div id="status" class="notice hidden"></div><button class="btn">Create business</button></form></div></div>`);$('#businessForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target);const store=data();store.vendors.push({id:id('vendor'),ownerId:currentUser.id,ownerName:form.get('ownerName'),name:form.get('name'),category:form.get('category'),description:form.get('description'),location:form.get('location'),hours:form.get('hours'),phone:form.get('phone'),bookingEnabled:form.get('bookingEnabled')==='on',status:'approved',verified:false,createdAt:now(),icon:'🏪'});const owner=store.users.find(user=>user.id===currentUser.id);owner.role='vendor';save(store);currentUser=owner;localStorage.setItem(SESSION_KEY,owner.id);location.href='vendor-dashboard.html'}}
function dashboard(vendorView=false){if(!requireUser(vendorView?'vendor-dashboard.html':'admin-dashboard.html'))return;const store=data();if(vendorView){const business=store.vendors.find(vendor=>vendor.ownerId===currentUser.id);const vendorIds=ownedVendorIds(currentUser.id);if(!business&&!vendorIds.size){render(`<div class="shell"><div class="empty"><h2>No business application yet</h2><p>Create a business to start receiving booking requests.</p><a class="btn" href="submit-business.html">Create business</a></div></div>`);return}const requests=store.bookings.filter(booking=>vendorIds.has(booking.vendorId));render(`<div class="shell dashboard"><div class="page-title"><div class="eyebrow">Vendor workspace</div><h1>Your business, at a glance.</h1><p class="muted">${esc(business?.name||'Demo services')} · ${esc(business?.status||'approved')}</p></div><div class="stats"><div class="card stat"><small class="muted">Bookings</small><b>${requests.length}</b></div><div class="card stat"><small class="muted">Pending</small><b>${requests.filter(item=>item.status==='pending').length}</b></div><div class="card stat"><small class="muted">Confirmed</small><b>${requests.filter(item=>item.status==='confirmed').length}</b></div></div><section class="card panel" style="margin-top:20px"><h2>Booking requests</h2>${bookingRows(requests,true)}</section></div>`);document.querySelectorAll('.booking-status').forEach(button=>button.onclick=()=>{changeBooking(button.dataset.id,button.dataset.status);dashboard(true)});return}
 if(currentUser.role!=='admin'){render(`<div class="shell"><div class="empty"><h2>Admin access required</h2><p>Use the internal admin account to manage applications and all requests.</p></div></div>`);return}const pending=store.vendors.filter(vendor=>vendor.status==='pending');render(`<div class="shell dashboard"><div class="page-title"><div class="eyebrow">Mission control</div><h1>Good evening, Admin 👋</h1><p class="muted">Internal requests and vendor applications.</p></div><div class="stats"><div class="card stat"><small class="muted">Users</small><b>${store.users.length}</b></div><div class="card stat"><small class="muted">Vendors</small><b>${store.vendors.length}</b></div><div class="card stat"><small class="muted">Bookings</small><b>${store.bookings.length}</b></div><div class="card stat"><small class="muted">Pending approvals</small><b>${pending.length}</b></div></div><div class="grid dashboard-grid"><section class="card panel"><h2>Vendor applications</h2>${pending.length?pending.map(vendor=>`<div class="booking-row"><span><b>${esc(vendor.name)}</b><br><small class="muted">${esc(vendor.category)} · ${esc(vendor.ownerName)}</small></span><span class="admin-actions"><button class="btn approve" data-id="${vendor.id}">Approve</button><button class="btn secondary reject" data-id="${vendor.id}">Reject</button></span></div>`).join(''):'<div class="empty">No vendor applications waiting.</div>'}</section><section class="card panel"><h2>Recent booking requests</h2>${bookingRows(store.bookings.slice(0,8))}</section></div></div>`);document.querySelectorAll('.approve').forEach(button=>button.onclick=()=>{const next=data();const vendor=next.vendors.find(item=>item.id===button.dataset.id);const owner=next.users.find(item=>item.id===vendor.ownerId);vendor.status='approved';vendor.verified=true;if(owner)owner.role='vendor';save(next);dashboard(false)});document.querySelectorAll('.reject').forEach(button=>button.onclick=()=>{const next=data();const vendor=next.vendors.find(item=>item.id===button.dataset.id);vendor.status='rejected';save(next);dashboard(false)})}
function startChat(vendor){if(!requireUser(`vendor.html?id=${vendor.id}`))return;const store=data();let conversation=store.conversations.find(item=>item.vendorId===vendor.id&&item.userId===currentUser.id);if(!conversation){conversation={id:id('chat'),userId:currentUser.id,vendorId:vendor.id,vendorName:vendor.name,lastMessage:'',updatedAt:now()};store.conversations.push(conversation);save(store)}location.href=`chat.html?id=${conversation.id}`}
function chat(){if(!requireUser('chat.html'))return;const activeId=new URLSearchParams(location.search).get('id');const store=data();const conversations=store.conversations.filter(item=>item.userId===currentUser.id||currentUser.role==='admin'||store.vendors.some(vendor=>vendor.id===item.vendorId&&vendor.ownerId===currentUser.id)).sort((a,b)=>b.updatedAt-a.updatedAt);const active=conversations.find(item=>item.id===activeId)||conversations[0];render(`<div class="shell section"><div class="card chat-layout"><aside class="conversation-list"><div class="panel"><b>Messages</b><p class="muted">Internal browser conversations</p></div><div id="conversationList">${conversations.length?conversations.map(conversation=>`<a class="conversation" href="chat.html?id=${conversation.id}"><div class="avatar">💬</div><span><b>${esc(conversation.vendorName)}</b><br><small class="muted">${esc(conversation.lastMessage||'Start a conversation')}</small></span></a>`).join(''):'<div class="empty">No conversations yet.</div>'}</div></aside><section><div class="panel"><b id="chatTitle">${active?esc(active.vendorName):'Choose a conversation'}</b><span class="badge"> ● Available</span></div><div id="messages" class="messages">${active?store.messages.filter(message=>message.conversationId===active.id).map(message=>`<div class="bubble ${message.senderId===currentUser.id?'mine':''}">${esc(message.text)}<br><small class="muted">${new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="empty">Say hello to begin.</div>':'<div class="empty">Choose a conversation to start chatting.</div>'}</div><form id="messageForm" class="message-form"><input id="messageInput" placeholder="Type a message…" ${active?'':'disabled'}><button class="btn" ${active?'':'disabled'}>Send</button></form></section></div></div>`);if(active){$('#messageForm').onsubmit=event=>{event.preventDefault();const input=$('#messageInput');const text=input.value.trim();if(!text)return;const next=data();next.messages.push({id:id('message'),conversationId:active.id,senderId:currentUser.id,text,createdAt:now(),read:false});const conversation=next.conversations.find(item=>item.id===active.id);conversation.lastMessage=text;conversation.updatedAt=now();save(next);chat()}}}
function boot(){
  const page=location.pathname.split('/').pop()||'index.html';
  const routes={
    'index.html':home,'vendors.html':directory,'vendor.html':profile,
    'request.html':request,'login.html':()=>authPage('login'),
    'register.html':()=>authPage('register'),'account.html':account,
    'bookings.html':bookings,'submit-business.html':submitBusiness,
    'vendor-dashboard.html':()=>dashboard(true),'vendor-bookings.html':()=>dashboard(true),
    'vendor-chat.html':chat,'admin-dashboard.html':()=>dashboard(false),'chat.html':chat
  };
  // Route functions render into #app and intentionally return nothing. Calling
  // home() with || here used to overwrite every route after it rendered.
  const renderPage=routes[page]||home;
  renderPage();
}
boot();
