// Clearly labelled local demo data. It appears before Firebase is configured.
export const demoVendors=[
{id:'demo-tiffin',name:'Aai’s Home Tiffin',category:'Tiffin',icon:'🍱',rating:4.8,location:'Khed Chowk, Shirwal',description:'Fresh Maharashtrian home-style meals delivered nearby.',bookingEnabled:true,phone:'919000000001',ownerId:'demo-owner-1',hours:'Mon–Sat · 8 AM – 8 PM',lat:18.151,lng:73.978},
{id:'demo-doctor',name:'Dr. Patil Family Clinic',category:'Doctors',icon:'🩺',rating:4.9,location:'Market Road, Shirwal',description:'Friendly family consultations and appointment slots.',bookingEnabled:true,phone:'919000000002',ownerId:'demo-owner-2',hours:'Mon–Sat · 9 AM – 7 PM',lat:18.153,lng:73.979},
{id:'demo-salon',name:'Glow & Go Salon',category:'Salon',icon:'✂️',rating:4.7,location:'Pune–Satara Road',description:'Haircuts, grooming and bridal-ready services.',bookingEnabled:true,phone:'919000000003',ownerId:'demo-owner-3',hours:'Daily · 10 AM – 8 PM',lat:18.149,lng:73.974},
{id:'demo-electric',name:'Shinde Electrical Works',category:'Electrical',icon:'💡',rating:4.6,location:'Shirwal MIDC',description:'Quick, dependable electrical repairs for homes.',bookingEnabled:false,phone:'919000000004',ownerId:'demo-owner-4',hours:'Daily · 8 AM – 7 PM'},
{id:'demo-laundry',name:'Circle Clean Laundry',category:'Laundry',icon:'🧺',rating:4.5,location:'Bazar Peth, Shirwal',description:'Wash, iron and doorstep laundry collection.',bookingEnabled:false,phone:'919000000005',ownerId:'demo-owner-5',hours:'Mon–Sun · 8 AM – 8 PM'},
{id:'demo-rickshaw',name:'Shirwal Ride Rickshaw',category:'Rickshaw',icon:'🛺',rating:4.6,location:'ST Stand, Shirwal',description:'Local rides and station pickup requests.',bookingEnabled:false,phone:'919000000006',ownerId:'demo-owner-6',hours:'Available today'},
{id:'demo-plumber',name:'Om Plumbing Services',category:'Plumbing',icon:'🔧',rating:4.7,location:'Guruwar Peth',description:'Leaks, fittings and same-day plumbing help.',bookingEnabled:false,phone:'919000000007',ownerId:'demo-owner-7',hours:'Daily · 9 AM – 6 PM'},
{id:'demo-travel',name:'Sai Tours & Travels',category:'Tours & Travels',icon:'🚐',rating:4.5,location:'Near Bus Stand',description:'Outstation cabs and comfortable group travel.',bookingEnabled:false,phone:'919000000008',ownerId:'demo-owner-8',hours:'Daily · 7 AM – 9 PM'}];
export const categories=['Tiffin','Laundry','Rickshaw','Doctors','Salon','Beauty Parlor','Electrical','Plumbing','Gas Mechanic','Refrigerator Repair','TV / LED Repair','Computer Repair','Xerox & Printing','Pest Control','Cleaning','House Shifting','Painting','Tours & Travels','Car Services','Car Wash','Real Estate','Shop Act License'];
export const demoServices=[{id:'haircut',vendorId:'demo-salon',name:'Haircut',price:'₹150 onwards',duration:'30 minutes',bookingEnabled:true},{id:'consult',vendorId:'demo-doctor',name:'General consultation',price:'₹300',duration:'20 minutes',bookingEnabled:true},{id:'tiffin',vendorId:'demo-tiffin',name:'Monthly tiffin plan',price:'₹90/day',duration:'Starts on your date',bookingEnabled:true}];
